pipeline {
    agent any

    environment {
        ANSIBLE_CONFIG="/home/ubuntu/ansible-config-mgt/deploy/ansible.cfg"
            }

    parameters {
        string (name: 'inventory', defaultValue: 'dev',  description: 'This is the inventory file for the environment to deploy configuration')
        }

    stages {
        stage("Initial cleanup") {
            steps {
                dir("/home/ubuntu/ansible-config-mgt/) {
                deleteDir()
                    }
                }
            }

        stage ('Checkout SCM') {
            steps{
                git branch: 'main', url: 'https://github.com/CtripleU/ansible-config-mgt.git'
            }
        }

        stage ('Prepare Ansible For Execution') {
            steps {
            sh 'echo /home/ubuntu/ansible-config-mgt/' 
            sh 'sed -i "3 a roles_path=/home/ubuntu/ansible-config-mgt/roles" /home/ubuntu/ansible-config-mgt/deploy/ansible.cfg'  
            }
        }

        stage ('Run Ansible playbook') {
            steps {
            ansiblePlaybook become: true, colorized: true, credentialsId: 'private-key', disableHostKeyChecking: true, installation: 'ansible', inventory: 'inventory/${inventory}', playbook: 'playbooks/site.yml'
            }
        }

        stage ('Clean Workspace after build') {
            steps {
            cleanWs(cleanWhenAborted: true, cleanWhenFailure: true, cleanWhenNotBuilt: true, cleanWhenUnstable: true, deleteDirs: true)
            }
        }
    }
}
